### ISSUE TITLE
Easy Website Payments

### ISSUE THREAD

**Issue by yeqbfgxjiq** [helpdao/help#3]
Add Wyre and/or Uniswap payment widget to [HelpDAO website](https://helpdao.org/) so that people can easily donate.

**Comment by yeqbfgxjiq** [comment]
Eventually we would like the experience to be where a Telegram bot asks creators of a help squad for the name of the squad and a description of it's goals. Then we can generate a link for the squad such as `squads.helpdao.org/{NAME-OF-SQUAD}` that autopopulates it with that name, description, and the fundraising product. Then the user can donate through the bot or the website directly.

**Comment by JackKnutson** [comment]
Implementing the [Hosted Widget ](https://pay.sendwyre.com/purchase ) would be the quickest and easiest solution. The "donate button" could just redirect there. 

Docs can be found here: https://docs.sendwyre.com/docs/hosted-widget-1

We can prefill the address of the DAO and make DAI the only currency available through the URL params. We can also redirect to the Discord/Telegram/Whatsapp after the user closes the widget. 

We should be able to lower our fees to cost. 

We also soft-launched international payments last week and can accept up to $500 per tx in these countries:

_Australia, Austria, Belgium, Canada, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hong Kong, Ireland, Italy, Latvia, Lithuania, Luxembourg, Mexico, The Netherlands, New Zealand, Norway, Poland, Portugal, Slovakia, Slovenia, Spain, Sweden, Switzerland_

In the US we can accept up to $250 per tx

I am going to have to discuss with our compliance team on how we should onboard the DAO/Squads. I will let you know what I hear back.

**Comment by JackKnutson** [comment]
We can keep this pretty darn simple. If we want to donate to separate squads we can just change the URL param to have each squad's address. No compliance needed for any of this. 😄 Build away!

If we want to create a simple bot I can invite whoever to the Wyre Zapier integration. It's super easy to create different bots for different social platforms.

**Comment by luisivan** [comment]
Boom, amazing!

> If we want to create a simple bot I can invite whoever to the Wyre Zapier integration. It's super easy to create different bots for different social platforms.

How does it work? Would it fire off a webhook once someone made a payment?

**Comment by JackKnutson** [comment]
We've put the Wyre endpoints in Zapier so you can easily connect it to a bunch of different applications. You could have it fire off a notification to any channel you want. 

<img width="943" alt="Screen Shot 2020-03-22 at 12 51 09 PM" src="https://user-images.githubusercontent.com/33010556/77256454-71204800-6c3c-11ea-908b-bc022384ba07.png">
<img width="897" alt="Screen Shot 2020-03-22 at 12 51 22 PM" src="https://user-images.githubusercontent.com/33010556/77256455-74b3cf00-6c3c-11ea-9c06-df41f015d34f.png">
<img width="951" alt="Screen Shot 2020-03-22 at 12 52 12 PM" src="https://user-images.githubusercontent.com/33010556/77256459-7b424680-6c3c-11ea-830a-2008be358e90.png">

**Comment by enriquegasch** [comment]
Mmmm? Direct payment, doesn't looks like crowdsourcing.

As transparency is key, groups should have a subset of goals with the subsequent cost of implementation.

And I think the donor should be able to choose from the different goals the one he wants to support with his money.

Maybe we could also work on getting this done.

What we will need to implement this later on?

**Comment by luisivan** [comment]
@drknudy this is amazing! We could easily plug that so we get a notifications in our Discord each time someone donates

**Comment by yeqbfgxjiq** [comment]
> Some more resources

## Onramps

[MoonPay](https://www.moonpay.io/)

[Ramp Instant - radically better crypto onboarding](https://instant.ramp.network/)

[Wyre - Crypto API for payments and KYC cryptocurrency verification](https://www.sendwyre.com/)

## Offramps

[Mooni](https://mooni.tech/)

## Both Ramps

[Local Cryptos](https://localcryptos.com/)

[Bisq - A decentralized bitcoin exchange network](https://bisq.network/)

**Comment by enriquegasch** [comment]
Ramp: low percentage taken
Mooni: No percentage taken
Wyre: They are on this with us, maybe they can give us a very good deal.

**Comment by marsrobertson** [comment]
I'm curious how do you resolve legal affairs?

I was checking in the UK, donations are treated as taxable income... Unless you are a charity. But charities have a whole entire universe of regulations attached.

We have some thoughts at @estoniaDAO about legal side of things, just curious if you have any thoughts on that?

The super fast cheap efficient crypto-on-off-fiat onramp can be an interesting project in itself.

**Comment by luisivan** [comment]
Well, depends on each help squad and how it's setup really @marsrobertson

**Comment by marsrobertson** [comment]
Thank you.

Different DAO, different groups, different countries, different jurisdictions, different legal frameworks, different enforceability...

I did some research in the UK 🇬🇧 and I did not found a single legal framework acceptable:
- donations being a taxable income, unless you are a charity
- a charity cannot benefit the trustees unless the benefit is accidental

We have a dedicated channel for legal affairs:
* https://www.notion.so/estoniadao/Legal-Squad-a570dd2cb9f2408ea8007c414cc372e0
* https://discord.gg/kKAbENX

# Bounty is live! 

### https://explorer.bounties.network/bounty/3925

![image](https://user-images.githubusercontent.com/44369284/77854776-2c6c5200-71e4-11ea-94ae-b72d012322b9.png)

Shill, shill, shill, we will surely use your solution and your experience ⚡️⚡️⚡️

**Comment by leckylao** [comment]
Hi @burrrata @luisivan ,

I am interested in the bounty but I have a different approach about the ramps, please review if that's what you want and if it's legible for the bounty then I can implement a demo for it. 

Onramp:

[Use GSN with Credit Card](https://docs.openzeppelin.com/gsn-provider/0.1/gsn-faq#can_i_use_this_with_credit_cards). As shown by using meta-transaction everyone can easily donate using credit card, their info. can be stored in the contract as email/discord handle. This approach also align with Aragon's rollout [Meta Txs: Adding support for meta transactions in aragon apps (Part 1)](https://github.com/aragon/aragonOS/pull/526) and [Meta Txs: Adding support for meta transactions in aragon apps (Part 2)](https://github.com/aragon/aragonOS/pull/527). Therefore in future they could do voting and other actions on Aragon. Which you can't do this with one-off payment solution like Wyre etc.

Offramp:

In the demo I can add the withdraw function which withdraw crypto to specific address. And I would suggest the following ways from crypto to fiat:
* [Crypto ATM](https://coinatmradar.com/countries/) I have tried this personally and I have good experience with it. It's good and fast for small amount, KYC is done with text message. 
* [Debit Card](https://tenx.tech/) There's multiple debit card options and I have one from TenX, this way you can just withdraw crypto to the debit card crypto address then you can use the debit card anywhere.

**Comment by luisivan** [comment]
Very good ideas here! @burrrata what do you think about eligibility for bounties? Specially around GSN with debit card integration inside Aragon

**Comment by yeqbfgxjiq** [comment]
> Very good ideas here! @burrrata what do you think about eligibility for bounties? Specially around GSN with debit card integration inside Aragon

This would be amazing. Checked with @sohkai and it sounds like integrating meta-tx would require contract upgrades and audits, however, so that's not exactly feasible within the timeline of this hackathon (sad...). So, for the purposes of this hackathon we want something that can be shipped (and tested with real users) by the end of the month. 

Is there a way to get some or most of this functionality without directly integrating with the core Aragon contracts?

**Comment by sohkai** [comment]
Integrating meta-tx (GSN, etc0 with an existing contract could be an interesting bounty on its own for this hackathon as well, but not sure if we can make more.

**Comment by leckylao** [comment]
> Integrating meta-tx (GSN, etc0 with an existing contract could be an interesting bounty on its own for this hackathon as well, but not sure if we can make more.

Hi @burrrata @sohkai , yes, I can make a demo for this and test it out with real user. It would be using meta-tx for the on-ramp as I mentioned before.

**Comment by leckylao** [comment]
Just checked the code on https://github.com/helpdao/donation-portal and looks like the on-ramp has already been done by added ramp and wyre, so I guess the bounty is not relevant anymore. Could you please clarify @burrrata @luisivan or let me know what else is needed in the bounty

**Comment by luisivan** [comment]
Yeah! This one has been done. I will close @burrrata
