### ISSUE TITLE
Add HelpDAO Template to the Aragon DAO deployment page

### ISSUE THREAD

**Issue by yeqbfgxjiq** [helpdao/help#6]
Once #4 and #1 are done, it would be great to add HelpDAO to the mainnet.aragon.org/#/create page so that people can easily spin them up.

> Just add a disclaimer that it's in beta or it's a community project or something.

**Comment by luisivan** [comment]
Squads will be launched directly from HelpDAO (custom frontends!) so this is not needed. Closing!
