### ISSUE TITLE
WhatsApp might need to be used instead of Telegram in Crimea & Russia

### ISSUE THREAD

**Issue by anastasiyabelyaeva** [helpdao/help#9]
Telegram is banned in Russia :( 
A few people still use it, but that limits the userbase massively. 

So instead of the bot inviting you to Telegram once you receive your token as a Donor, we could just have a link to that Whatsapp group that shows on the page once the person has donated funds? That would just be for regions where people don't use telegram!

**Comment by luisivan** [comment]
We may want to simplify the product even more and go from donation -> get token -> get invite link. Invite link can be WhatsApp/Telegram/WeChat/etc.

**Comment by luisivan** [comment]
We kept it agnostic -- closing for now!
